import { type Theme } from 'theme-token-manager'

const defaultFamily = {
  headline: 'Montserrat',
  content: 'Montserrat',
}

const defaultHeight = {
  '4xl': 74,
  '3xl': 58,
  '2xl': 46,
  xl: 38,
  lg: 30,
  md: 24,
  base: 20,
  sm: 18,
  xs: 16,
}

const defaultSpacing = {
  lg: 2,
  md: 1,
  xs: 0,
  base: 0,
}

const defaultWeight = {
  regular: 400,
  medium: 500,
  semiBold: 600,
  bold: 700,
}

const defaultParagraphSpacing = {
  base: 20,
}

const defaultDimensions = {
  '0': 0,
  '25': 1,
  '50': 2,
  '100': 4,
  '150': 6,
  '200': 8,
  '300': 12,
  '400': 16,
  '500': 20,
  '600': 24,
  '700': 28,
  '800': 32,
  '900': 36,
  '1000': 40,
  '1100': 48,
  '1200': 56,
  '1300': 64,
  '1400': 72,
  '1500': 96,
  '1600': 128,
  '1700': 256,
  '1800': 512,
  '1900': 1024,
}

export const algarTheme: Theme = {
  id: 'algar',
  name: 'algar',
  base: {
    color: {
      collection: {
        primary: {
          '1200': '#000202',
          '1100': '#061D19',
          '1000': '#0C3830',
          '900': '#115348',
          '800': '#176D5F',
          '700': '#1D8876',
          '600': '#22A38E',
          '500': '#28bea5',
          '400': '#4DC9B4',
          '300': '#71D4C4',
          '200': '#96DFD3',
          '150': '#BAEAE2',
          '100': '#DFF5F2',
        },
        secondary: {
          '1200': '#010302',
          '1100': '#08271A',
          '1000': '#0F4B2C',
          '900': '#166F36',
          '800': '#1D9339',
          '700': '#24B736',
          '600': '#2BDB2B',
          '500': '#4bff32',
          '400': '#68FF53',
          '300': '#85FF74',
          '200': '#A1FF94',
          '150': '#BEFFB5',
          '100': '#DBFFD6',
        },
        blue: {
          '100': '#e6f2fa',
          '150': '#b3d8f1',
          '200': '#80bde8',
          '300': '#4da3df',
          '400': '#1a88d6',
          '500': '#0070d2',
          '600': '#005bb5',
          '700': '#004799',
          '800': '#00337d',
          '900': '#002062',
          '1000': '#00104b',
          '1100': '#000833',
          '1200': '#00041a',
        },
        indigo: {
          '100': '#ede7fb',
          '150': '#d1c2f6',
          '200': '#b59cf2',
          '300': '#9976ed',
          '400': '#7d51e9',
          '500': '#6610f2',
          '600': '#520dc2',
          '700': '#3d0991',
          '800': '#290661',
          '900': '#140330',
          '1000': '#0a011a',
          '1100': '#05000d',
          '1200': '#020005',
        },
        purple: {
          '100': '#f3eaf8',
          '150': '#e0c8ee',
          '200': '#cca5e4',
          '300': '#b982da',
          '400': '#a65fd0',
          '500': '#6f42c1',
          '600': '#59349a',
          '700': '#432673',
          '800': '#2c184c',
          '900': '#160c26',
          '1000': '#0b0613',
          '1100': '#05030a',
          '1200': '#020105',
        },
        pink: {
          '100': '#fde6f1',
          '150': '#fabfdc',
          '200': '#f799c7',
          '300': '#f473b2',
          '400': '#f14d9d',
          '500': '#e83e8c',
          '600': '#b8306e',
          '700': '#892350',
          '800': '#591632',
          '900': '#2c0b19',
          '1000': '#16050d',
          '1100': '#0b0206',
          '1200': '#050103',
        },
        red: {
          '100': '#fbe6e6',
          '150': '#f6b3b3',
          '200': '#f28080',
          '300': '#ed4d4d',
          '400': '#e91a1a',
          '500': '#c00',
          '600': '#990000',
          '700': '#730000',
          '800': '#4d0000',
          '900': '#260000',
          '1000': '#130000',
          '1100': '#0a0000',
          '1200': '#050000',
        },
        orange: {
          '100': '#fff0e6',
          '150': '#ffd9b3',
          '200': '#ffc280',
          '300': '#ffab4d',
          '400': '#ff941a',
          '500': '#fd7e14',
          '600': '#cc6510',
          '700': '#994c0c',
          '800': '#663308',
          '900': '#331904',
          '1000': '#1a0c02',
          '1100': '#0d0601',
          '1200': '#050300',
        },
        yellow: {
          '100': '#fffbe6',
          '150': '#fff3b3',
          '200': '#ffeb80',
          '300': '#ffe34d',
          '400': '#ffdb1a',
          '500': '#ffc107',
          '600': '#cc9a06',
          '700': '#997405',
          '800': '#664d03',
          '900': '#332701',
          '1000': '#1a1400',
          '1100': '#0d0a00',
          '1200': '#050400',
        },
        green: {
          '100': '#e6f7ed',
          '150': '#b3e6cb',
          '200': '#80d6a9',
          '300': '#4dc687',
          '400': '#26b96f',
          '500': '#008827',
          '600': '#00691f',
          '700': '#004a17',
          '800': '#002b0f',
          '900': '#001507',
          '1000': '#000b03',
          '1100': '#000601',
          '1200': '#000300',
        },
        teal: {
          '100': '#e6fcf7',
          '150': '#b3f7e7',
          '200': '#80f2d7',
          '300': '#4dedc7',
          '400': '#1ae8b7',
          '500': '#20c997',
          '600': '#1aa37a',
          '700': '#137d5c',
          '800': '#0d573e',
          '900': '#062120',
          '1000': '#031110',
          '1100': '#010908',
          '1200': '#000404',
        },
        cyan: {
          '100': '#e6fafd',
          '150': '#b3f0fa',
          '200': '#80e6f7',
          '300': '#4ddcf4',
          '400': '#1ad2f1',
          '500': '#17a2b8',
          '600': '#128294',
          '700': '#0e616f',
          '800': '#09414b',
          '900': '#052026',
          '1000': '#021014',
          '1100': '#01080a',
          '1200': '#000405',
        },
        gray: {
          '100': '#f8f9fa',
          '150': '#e9ecef',
          '200': '#dee2e6',
          '300': '#ced4da',
          '400': '#adb5bd',
          '500': '#6c757d',
          '600': '#495057',
          '700': '#343a40',
          '800': '#23272b',
          '900': '#121416',
          '1000': '#090a0b',
          '1100': '#050505',
          '1200': '#020202',
        },
        white: {
          '100': '#fff',
          '150': '#fff',
          '200': '#fff',
          '300': '#fff',
          '400': '#fff',
          '500': '#fff',
          '600': '#f8f9fa',
          '700': '#e9ecef',
          '800': '#dee2e6',
          '900': '#ced4da',
          '1000': '#adb5bd',
          '1100': '#6c757d',
          '1200': '#343a40',
        },
        dark: {
          '100': '#343a40',
          '150': '#23272b',
          '200': '#121416',
          '300': '#090a0b',
          '400': '#050505',
          '500': '#020202',
          '600': '#000000',
          '700': '#000000',
          '800': '#000000',
          '900': '#000000',
          '1000': '#000000',
          '1100': '#000000',
          '1200': '#000000',
        },
      },
      foundations: {
        black: '#000000',
        white: '#ffffff',
      },
    },
    font: {
      family: defaultFamily,
      height: defaultHeight,
      spacing: defaultSpacing,
      paragraphSpacing: defaultParagraphSpacing,
      size: {
        '4xl': 72,
        '3xl': 56,
        '2xl': 44,
        xl: 36,
        lg: 28,
        md: 22,
        base: 18,
        sm: 16,
        xs: 14,
      },
      weight: defaultWeight,
    },
    size: {
      dimension: defaultDimensions,
    },
  },
  color: {
    primary: 'primary',
    secondary: 'secondary',
    accent: 'blue',
    error: 'red',
    information: 'cyan',
    success: 'green',
    warning: 'yellow',
    'neutral-dark': 'gray',
    'neutral-light': 'white',
  },
  font: {
    family: {
      body: 'content',
      bodyShort: 'content',
      bodyLong: 'content',
      label: 'content',
      labelLong: 'content',
      h1: 'headline',
      h2: 'headline',
      h3: 'headline',
      h4: 'headline',
      h5: 'headline',
      h6: 'headline',
      hyperlink: 'content',
      hyperlinkHover: 'content',
      caption: 'content',
    },
    spacing: {
      hyperlink: 'base',
      hyperlinkHover: 'base',
      body: 'base',
      bodyShort: 'md',
      bodyLong: 'base',
      label: 'md',
      labelLong: 'md',
      h1: 'xs',
      h2: 'xs',
      h3: 'xs',
      h4: 'xs',
      h5: 'xs',
      h6: 'xs',
      caption: 'xs',
    },
    height: {
      hyperlink: 'sm',
      hyperlinkHover: 'sm',
      bodyShort: 'xs',
      body: 'sm',
      bodyLong: 'base',
      label: 'sm',
      labelLong: 'base',
      h1: '4xl',
      h2: '3xl',
      h3: '2xl',
      h4: 'xl',
      h5: 'lg',
      h6: 'md',
      caption: 'xs',
    },
    size: {
      hyperlink: 'base',
      hyperlinkHover: 'base',
      bodyShort: 'xs',
      body: 'sm',
      bodyLong: 'base',
      label: 'base',
      labelLong: 'base',
      h1: '4xl',
      h2: '3xl',
      h3: '2xl',
      h4: 'xl',
      h5: 'lg',
      h6: 'md',
      caption: 'xs',
    },
    weight: {
      hyperlink: 'medium',
      hyperlinkHover: 'medium',
      bodyShort: 'regular',
      body: 'regular',
      bodyLong: 'regular',
      label: 'medium',
      labelLong: 'medium',
      h1: 'bold',
      h2: 'bold',
      h3: 'semiBold',
      h4: 'semiBold',
      h5: 'semiBold',
      h6: 'semiBold',
      caption: 'regular',
    },
    paragraphSpacing: {
      hyperlink: 'base',
      hyperlinkHover: 'base',
      bodyShort: 'base',
      body: 'base',
      bodyLong: 'base',
      label: 'base',
      labelLong: 'base',
      h1: 'base',
      h2: 'base',
      h3: 'base',
      h4: 'base',
      h5: 'base',
      h6: 'base',
      caption: 'base',
    },
  },
  size: {
    border: {
      width: {
        xs: 50,
        sm: 100,
        md: 150,
      },
      radius: {
        none: 0,
        '3xs': 50,
        '2xs': 100,
        xs: 150,
        sm: 200,
        md: 300,
        lg: 400,
        xl: 500,
        '2xl': 600,
        '3xl': 700,
        '4xl': 800,
        pill: 1900,
      },
    },
    spacing: {
      '4xs': 50,
      '3xs': 100,
      '2xs': 200,
      xs: 300,
      sm: 400,
      md: 500,
      lg: 600,
      xl: 800,
      '2xl': 1000,
      '3xl': 1100,
      '4xl': 1300,
    },
  },
  palette: {
    dark: {
      surface: {
        'primary-default': { color: 'primary', scale: 600 },
        'primary-defaultHover': { color: 'primary', scale: 400 },
        'primary-defaultSubtle': { color: 'primary', scale: 800 },
        'primary-defaultSubtleHover': { color: 'primary', scale: 700 },
        'primary-defaultSubtleHoverAlt': { color: 'primary', scale: 800 },
        'secondary-default': { color: 'secondary', scale: 500 },
        'secondary-defaultHover': { color: 'secondary', scale: 400 },
        'secondary-defaultSubtle': { color: 'secondary', scale: 400 },
        'secondary-defaultSubtleHover': { color: 'secondary', scale: 700 },
        'disabled-default': { color: 'neutral-dark', scale: 600 },
        'error-default': { color: 'error', scale: 700 },
        'error-defaultHover': { color: 'error', scale: 800 },
        'error-defaultSubtle': { color: 'error', scale: 900 },
        'error-defaultSubtleHover': { color: 'error', scale: 1000 },
        'success-default': { color: 'success', scale: 700 },
        'success-defaultHover': { color: 'success', scale: 800 },
        'success-defaultSubtle': { color: 'success', scale: 900 },
        'success-defaultSubtleHover': { color: 'success', scale: 1000 },
        'information-default': { color: 'information', scale: 700 },
        'information-defaultHover': { color: 'information', scale: 800 },
        'information-defaultSubtle': { color: 'information', scale: 900 },
        'information-defaultSubtleHover': { color: 'information', scale: 1000 },
        'warning-default': { color: 'warning', scale: 700 },
        'warning-defaultHover': { color: 'warning', scale: 800 },
        'warning-defaultSubtle': { color: 'warning', scale: 900 },
        'warning-defaultSubtleHover': { color: 'warning', scale: 1000 },
        default: { color: 'primary', scale: 1100 },
        page: { color: 'primary', scale: 1000 },
        pageAlternative: { color: 'primary', scale: 1000 },
        alternative: { color: 'primary', scale: 900 },
      },
      text: {
        'primary-onColor': { color: 'foundation.white' },
        'primary-onColorHover': { color: 'foundation.white' },
        'primary-onColorSubtle': { color: 'secondary', scale: 400 },
        'primary-onColorSubtleHover': { color: 'secondary', scale: 500 },
        'primary-default': { color: 'foundation.white' },
        'primary-defaultHover': { color: 'foundation.white' },
        'secondary-onColor': { color: 'primary', scale: 1100 },
        'secondary-onColorHover': { color: 'primary', scale: 900 },
        'secondary-onColorSubtle': { color: 'foundation.white' },
        'secondary-onColorSubtleHover': {
          color: 'foundation.white',
        },
        'secondary-default': { color: 'secondary', scale: 100 },
        'secondary-defaultHover': { color: 'secondary', scale: 300 },
        'disabled-default': { color: 'neutral-light', scale: 300 },
        'disabled-onColor': { color: 'neutral-light', scale: 300 },
        'error-onColor': { color: 'error', scale: 400 },
        'error-onColorHover': { color: 'error', scale: 500 },
        'error-onColorSubtle': { color: 'error', scale: 300 },
        'error-onColorSubtleHover': { color: 'error', scale: 400 },
        'error-default': { color: 'error', scale: 300 },
        'error-defaultHover': { color: 'error', scale: 400 },
        'success-onColor': { color: 'success', scale: 400 },
        'success-onColorHover': { color: 'success', scale: 500 },
        'success-onColorSubtle': { color: 'success', scale: 300 },
        'success-onColorSubtleHover': { color: 'success', scale: 400 },
        'success-default': { color: 'success', scale: 300 },
        'success-defaultHover': { color: 'success', scale: 400 },
        'information-onColor': { color: 'information', scale: 400 },
        'information-onColorHover': { color: 'information', scale: 500 },
        'information-onColorSubtle': { color: 'information', scale: 300 },
        'information-onColorSubtleHover': { color: 'information', scale: 400 },
        'information-default': { color: 'information', scale: 300 },
        'information-defaultHover': { color: 'information', scale: 400 },
        'warning-onColor': { color: 'warning', scale: 400 },
        'warning-onColorHover': { color: 'warning', scale: 500 },
        'warning-onColorSubtle': { color: 'warning', scale: 300 },
        'warning-onColorSubtleHover': { color: 'warning', scale: 400 },
        'warning-default': { color: 'warning', scale: 300 },
        'warning-defaultHover': { color: 'warning', scale: 400 },
        'default-body': { color: 'foundation.white' },
        'default-hero': { color: 'foundation.white' },
        'default-heading': { color: 'foundation.white' },
        'default-caption': { color: 'secondary', scale: 400 },
        'default-placeholder': { color: 'secondary', scale: 400 },
        'onColor-hero': { color: 'foundation.white' },
        'onColor-heading': { color: 'foundation.white' },
        'onColor-body': { color: 'foundation.white' },
        'onColor-caption': { color: 'secondary', scale: 400 },
        'onColor-placeholder': { color: 'secondary', scale: 400 },
        'accent-default': { color: 'accent', scale: 400 },
        'accent-defaultHover': { color: 'accent', scale: 500 },
        'accent-onColor': { color: 'accent', scale: 400 },
        'accent-onColorHover': { color: 'accent', scale: 500 },
        'accent-onColorSubtle': { color: 'accent', scale: 300 },
        'accent-onColorSubtleHover': { color: 'accent', scale: 400 },
      },
      icon: {
        'primary-onColor': { color: 'foundation.white' },
        'primary-onColorHover': { color: 'foundation.white' },
        'primary-onColorSubtle': { color: 'secondary', scale: 400 },
        'primary-onColorSubtleHover': { color: 'secondary', scale: 500 },
        'primary-default': { color: 'foundation.white' },
        'primary-defaultHover': { color: 'foundation.white' },
        'primary-defaultSubtle': { color: 'foundation.white' },
        'primary-defaultSubtleHover': { color: 'foundation.white' },
        'secondary-onColor': { color: 'foundation.white' },
        'secondary-onColorHover': { color: 'foundation.white' },
        'secondary-onColorSubtle': { color: 'error', scale: 300 },
        'secondary-onColorSubtleHover': { color: 'error', scale: 400 },
        'secondary-default': { color: 'secondary', scale: 100 },
        'secondary-defaultHover': { color: 'secondary', scale: 300 },
        'disabled-default': { color: 'neutral-light', scale: 300 },
        'disabled-onColor': { color: 'neutral-light', scale: 300 },
        'error-onColor': { color: 'error', scale: 400 },
        'error-onColorHover': { color: 'error', scale: 500 },
        'error-onColorSubtle': { color: 'error', scale: 300 },
        'error-onColorSubtleHover': { color: 'error', scale: 400 },
        'error-default': { color: 'error', scale: 300 },
        'error-defaultHover': { color: 'error', scale: 400 },
        'success-onColor': { color: 'success', scale: 400 },
        'success-onColorHover': { color: 'success', scale: 500 },
        'success-onColorSubtle': { color: 'success', scale: 300 },
        'success-onColorSubtleHover': { color: 'success', scale: 400 },
        'success-default': { color: 'success', scale: 300 },
        'success-defaultHover': { color: 'success', scale: 400 },
        'information-onColor': { color: 'information', scale: 400 },
        'information-onColorHover': { color: 'information', scale: 500 },
        'information-onColorSubtle': { color: 'information', scale: 300 },
        'information-onColorSubtleHover': { color: 'information', scale: 400 },
        'information-default': { color: 'information', scale: 300 },
        'information-defaultHover': { color: 'information', scale: 400 },
        'warning-onColor': { color: 'warning', scale: 400 },
        'warning-onColorHover': { color: 'warning', scale: 500 },
        'warning-onColorSubtle': { color: 'warning', scale: 300 },
        'warning-onColorSubtleHover': { color: 'warning', scale: 400 },
        'warning-default': { color: 'warning', scale: 300 },
        'warning-defaultHover': { color: 'warning', scale: 400 },
      },
      border: {
        'primary-default': { color: 'primary', scale: 900 },
        'primary-defaultHover': { color: 'primary', scale: 800 },
        'primary-defaultSubtle': { color: 'primary', scale: 700 },
        'primary-defaultSubtleHover': { color: 'primary', scale: 600 },
        'primary-focus': { color: 'primary', scale: 900 },
        'error-default': { color: 'error', scale: 900 },
        'error-defaultHover': { color: 'error', scale: 800 },
        'error-defaultSubtle': { color: 'error', scale: 700 },
        'error-defaultSubtleHover': { color: 'error', scale: 600 },
        'error-focus': { color: 'error', scale: 900 },
        'success-default': { color: 'success', scale: 900 },
        'success-defaultHover': { color: 'success', scale: 800 },
        'success-defaultSubtle': { color: 'success', scale: 700 },
        'success-defaultSubtleHover': { color: 'success', scale: 600 },
        'success-focus': { color: 'success', scale: 900 },
        'information-default': { color: 'information', scale: 900 },
        'information-defaultHover': { color: 'information', scale: 800 },
        'information-defaultSubtle': { color: 'information', scale: 700 },
        'information-defaultSubtleHover': { color: 'information', scale: 600 },
        'information-focus': { color: 'information', scale: 900 },
        'warning-default': { color: 'warning', scale: 900 },
        'warning-defaultHover': { color: 'warning', scale: 800 },
        'warning-defaultSubtle': { color: 'warning', scale: 700 },
        'warning-defaultSubtleHover': { color: 'warning', scale: 600 },
        'warning-focus': { color: 'warning', scale: 900 },
        'secondary-default': { color: 'secondary', scale: 900 },
        'secondary-defaultHover': { color: 'secondary', scale: 800 },
        'secondary-defaultSubtle': { color: 'secondary', scale: 700 },
        'secondary-defaultSubtleHover': { color: 'secondary', scale: 600 },
        'secondary-focus': { color: 'secondary', scale: 900 },
        disabled: { color: 'neutral-light', scale: 1000 },
        'disabled-onColor': { color: 'neutral-light', scale: 200 },
        default: { color: 'neutral-dark', scale: 800 },
        'default-onColor': { color: 'neutral-light', scale: 800 },
      },
    },
    light: {
      surface: {
        'primary-default': { color: 'primary', scale: 700 },
        'primary-defaultHover': { color: 'primary', scale: 500 },
        'primary-defaultSubtle': { color: 'primary', scale: 100 },
        'primary-defaultSubtleHover': { color: 'primary', scale: 200 },
        'primary-defaultSubtleHoverAlt': { color: 'primary', scale: 200 },
        'secondary-default': { color: 'secondary', scale: 600 },
        'secondary-defaultHover': { color: 'secondary', scale: 500 },
        'secondary-defaultSubtle': { color: 'secondary', scale: 100 },
        'secondary-defaultSubtleHover': { color: 'secondary', scale: 200 },
        'disabled-default': { color: 'neutral-dark', scale: 500 },
        'error-default': { color: 'error', scale: 200 },
        'error-defaultHover': { color: 'error', scale: 300 },
        'error-defaultSubtle': { color: 'error', scale: 100 },
        'error-defaultSubtleHover': { color: 'error', scale: 150 },
        'success-default': { color: 'success', scale: 200 },
        'success-defaultHover': { color: 'success', scale: 300 },
        'success-defaultSubtle': { color: 'success', scale: 100 },
        'success-defaultSubtleHover': { color: 'success', scale: 150 },
        'information-default': { color: 'information', scale: 200 },
        'information-defaultHover': { color: 'information', scale: 300 },
        'information-defaultSubtle': { color: 'information', scale: 100 },
        'information-defaultSubtleHover': { color: 'information', scale: 150 },
        'warning-default': { color: 'warning', scale: 200 },
        'warning-defaultHover': { color: 'warning', scale: 300 },
        'warning-defaultSubtle': { color: 'warning', scale: 100 },
        'warning-defaultSubtleHover': { color: 'warning', scale: 150 },
        default: { color: 'foundation.white' },
        page: { color: 'foundation.white' },
        pageAlternative: { color: 'primary', scale: 1000 },
        alternative: { color: 'neutral-light', scale: 100 },
      },
      text: {
        'primary-onColor': { color: 'foundation.white' },
        'primary-onColorHover': { color: 'foundation.white' },
        'primary-onColorSubtle': { color: 'primary', scale: 900 },
        'primary-onColorSubtleHover': { color: 'primary', scale: 1000 },
        'primary-default': { color: 'primary', scale: 800 },
        'primary-defaultHover': { color: 'primary', scale: 900 },
        'secondary-onColor': { color: 'foundation.white' },
        'secondary-onColorHover': { color: 'foundation.white' },
        'secondary-onColorSubtle': { color: 'secondary', scale: 800 },
        'secondary-onColorSubtleHover': { color: 'secondary', scale: 900 },
        'secondary-default': { color: 'secondary', scale: 800 },
        'secondary-defaultHover': { color: 'secondary', scale: 900 },
        'disabled-default': { color: 'neutral-dark', scale: 400 },
        'disabled-onColor': { color: 'foundation.white' },
        'error-onColor': { color: 'neutral-light', scale: 100 },
        'error-onColorHover': { color: 'neutral-light', scale: 200 },
        'error-onColorSubtle': { color: 'error', scale: 700 },
        'error-onColorSubtleHover': { color: 'error', scale: 800 },
        'error-default': { color: 'error', scale: 800 },
        'error-defaultHover': { color: 'error', scale: 900 },
        'success-onColor': { color: 'neutral-light', scale: 100 },
        'success-onColorHover': { color: 'neutral-light', scale: 200 },
        'success-onColorSubtle': { color: 'success', scale: 800 },
        'success-onColorSubtleHover': { color: 'success', scale: 900 },
        'success-default': { color: 'success', scale: 800 },
        'success-defaultHover': { color: 'success', scale: 900 },
        'information-onColor': { color: 'neutral-light', scale: 100 },
        'information-onColorHover': { color: 'neutral-light', scale: 200 },
        'information-onColorSubtle': { color: 'information', scale: 800 },
        'information-onColorSubtleHover': { color: 'information', scale: 900 },
        'information-default': { color: 'information', scale: 800 },
        'information-defaultHover': { color: 'information', scale: 900 },
        'warning-onColor': { color: 'neutral-light', scale: 100 },
        'warning-onColorHover': { color: 'neutral-light', scale: 200 },
        'warning-onColorSubtle': { color: 'warning', scale: 800 },
        'warning-onColorSubtleHover': { color: 'warning', scale: 900 },
        'warning-default': { color: 'warning', scale: 800 },
        'warning-defaultHover': { color: 'warning', scale: 900 },
        'default-body': { color: 'neutral-dark', scale: 900 },
        'default-hero': { color: 'neutral-dark', scale: 1100 },
        'default-heading': { color: 'neutral-dark', scale: 1100 },
        'default-caption': { color: 'neutral-dark', scale: 700 },
        'default-placeholder': { color: 'neutral-dark', scale: 700 },
        'onColor-hero': { color: 'neutral-light', scale: 100 },
        'onColor-heading': { color: 'neutral-light', scale: 100 },
        'onColor-body': { color: 'neutral-light', scale: 100 },
        'onColor-caption': { color: 'neutral-light', scale: 200 },
        'onColor-placeholder': { color: 'neutral-light', scale: 300 },
        'accent-onColor': { color: 'neutral-light', scale: 100 },
        'accent-onColorHover': { color: 'neutral-light', scale: 200 },
        'accent-onColorSubtle': { color: 'accent', scale: 800 },
        'accent-onColorSubtleHover': { color: 'accent', scale: 900 },
        'accent-default': { color: 'accent', scale: 800 },
        'accent-defaultHover': { color: 'accent', scale: 900 },
      },
      icon: {
        'primary-onColor': { color: 'primary', scale: 100 },
        'primary-onColorHover': { color: 'primary', scale: 200 },
        'primary-onColorSubtle': { color: 'primary', scale: 900 },
        'primary-onColorSubtleHover': { color: 'primary', scale: 1000 },
        'primary-default': { color: 'primary', scale: 800 },
        'primary-defaultHover': { color: 'primary', scale: 900 },
        'primary-defaultSubtle': { color: 'foundation.white' },
        'primary-defaultSubtleHover': { color: 'foundation.white' },
        'secondary-onColor': { color: 'secondary', scale: 800 },
        'secondary-onColorHover': { color: 'secondary', scale: 900 },
        'secondary-onColorSubtle': { color: 'secondary', scale: 800 },
        'secondary-onColorSubtleHover': { color: 'secondary', scale: 900 },
        'secondary-default': { color: 'secondary', scale: 800 },
        'secondary-defaultHover': { color: 'secondary', scale: 900 },
        'disabled-default': { color: 'neutral-light', scale: 600 },
        'disabled-onColor': { color: 'foundation.white' },
        'error-onColor': { color: 'neutral-light', scale: 100 },
        'error-onColorHover': { color: 'neutral-light', scale: 200 },
        'error-onColorSubtle': { color: 'error', scale: 700 },
        'error-onColorSubtleHover': { color: 'error', scale: 800 },
        'error-default': { color: 'error', scale: 800 },
        'error-defaultHover': { color: 'error', scale: 900 },
        'success-onColor': { color: 'neutral-light', scale: 100 },
        'success-onColorHover': { color: 'neutral-light', scale: 200 },
        'success-onColorSubtle': { color: 'success', scale: 800 },
        'success-onColorSubtleHover': { color: 'success', scale: 900 },
        'success-default': { color: 'success', scale: 800 },
        'success-defaultHover': { color: 'success', scale: 900 },
        'information-onColor': { color: 'neutral-light', scale: 100 },
        'information-onColorHover': { color: 'neutral-light', scale: 200 },
        'information-onColorSubtle': { color: 'information', scale: 800 },
        'information-onColorSubtleHover': { color: 'information', scale: 900 },
        'information-default': { color: 'information', scale: 800 },
        'information-defaultHover': { color: 'information', scale: 900 },
        'warning-onColor': { color: 'neutral-light', scale: 100 },
        'warning-onColorHover': { color: 'neutral-light', scale: 200 },
        'warning-onColorSubtle': { color: 'warning', scale: 800 },
        'warning-onColorSubtleHover': { color: 'warning', scale: 900 },
        'warning-default': { color: 'warning', scale: 800 },
        'warning-defaultHover': { color: 'warning', scale: 900 },
      },
      border: {
        'primary-default': { color: 'primary', scale: 800 },
        'primary-defaultHover': { color: 'primary', scale: 900 },
        'primary-defaultSubtle': { color: 'primary', scale: 300 },
        'primary-defaultSubtleHover': { color: 'primary', scale: 500 },
        'primary-focus': { color: 'primary', scale: 900 },
        'error-default': { color: 'error', scale: 800 },
        'error-defaultHover': { color: 'error', scale: 900 },
        'error-defaultSubtle': { color: 'error', scale: 150 },
        'error-defaultSubtleHover': { color: 'error', scale: 300 },
        'error-focus': { color: 'error', scale: 800 },
        'success-default': { color: 'success', scale: 800 },
        'success-defaultHover': { color: 'success', scale: 900 },
        'success-defaultSubtle': { color: 'success', scale: 150 },
        'success-defaultSubtleHover': { color: 'success', scale: 300 },
        'success-focus': { color: 'success', scale: 800 },
        'warning-default': { color: 'warning', scale: 800 },
        'warning-defaultHover': { color: 'warning', scale: 900 },
        'warning-defaultSubtle': { color: 'warning', scale: 150 },
        'warning-defaultSubtleHover': { color: 'warning', scale: 300 },
        'warning-focus': { color: 'warning', scale: 800 },
        'information-default': { color: 'information', scale: 800 },
        'information-defaultHover': { color: 'information', scale: 900 },
        'information-defaultSubtle': { color: 'information', scale: 150 },
        'information-defaultSubtleHover': { color: 'information', scale: 300 },
        'information-focus': { color: 'information', scale: 800 },
        'secondary-default': { color: 'secondary', scale: 800 },
        'secondary-defaultHover': { color: 'secondary', scale: 900 },
        'secondary-defaultSubtle': { color: 'secondary', scale: 300 },
        'secondary-defaultSubtleHover': { color: 'secondary', scale: 500 },
        'secondary-focus': { color: 'secondary', scale: 900 },
        disabled: { color: 'neutral-light', scale: 200 },
        'disabled-onColor': { color: 'neutral-light', scale: 900 },
        default: { color: 'neutral-dark', scale: 200 },
        'default-onColor': { color: 'foundation.white' },
      },
    },
  },
}
