import { colors, type Theme } from 'theme-token-manager'

const defaultFamily = {
  headline: 'Plus Jakarta Sans',
  content: 'Plus Jakarta Sans',
}

const defaultHeight = {
  '4xl': 72,
  '3xl': 56,
  '2xl': 44,
  xl: 36,
  lg: 28,
  md: 22,
  base: 18,
  sm: 16,
  xs: 14,
}

const defaultSpacing = {
  lg: 2,
  md: 1,
  xs: 0,
  base: 0,
}

const defaultWeight = {
  regular: 500,
  medium: 600,
  semiBold: 700,
  bold: 800,
}

const defaultParagraphSpacing = {
  base: 20,
}

const defaultDimensions = {
  '0': 0,
  '25': 1,
  '50': 2,
  '100': 4,
  '150': 6,
  '200': 8,
  '300': 12,
  '400': 16,
  '500': 20,
  '600': 24,
  '700': 28,
  '800': 32,
  '900': 36,
  '1000': 40,
  '1100': 48,
  '1200': 56,
  '1300': 64,
  '1400': 72,
  '1500': 96,
  '1600': 128,
  '1700': 256,
  '1800': 512,
  '1900': 1024,
}

export const nioTheme: Theme = {
  id: 'nio',
  name: 'nio',
  base: {
    color: {
      collection: {
        black: {
          '100': '#f5f5f5',
          '150': '#e0e0e0',
          '200': '#bdbdbd',
          '300': '#9e9e9e',
          '400': '#757575',
          '500': '#616161',
          '600': '#424242',
          '700': '#212121',
          '800': '#141414',
          '900': '#0a0a0a',
          '1000': '#000000',
          '1100': '#000000',
          '1200': '#000000',
        },
        nioGreen: {
          '1200': '#041002',
          '1100': '#0A2805',
          '1000': '#104008',
          '900': '#15580C',
          '800': '#1B700F',
          '700': '#218812',
          '600': '#27a015',
          '500': '#49AF39',
          '400': '#6ABD5E',
          '300': '#8BCC82',
          '200': '#ADDBA6',
          '150': '#CEEACA',
          '100': '#F0F8EF',
        },
        sand: {
          '100': '#f6f2ee',
          '150': '#f6f2ee',
          '200': '#d8e1d1',
          '300': '#a7ac98',
          '400': '#5c5f54',
          '500': '#40423a',
          '600': '#e0e0e0',
          '700': '#f8f7f0',
          '800': '#f0f5eb',
          '900': '#f5f5f5',
          '1000': '#f7f7f7',
          '1100': '#c7c7c7',
          '1200': '#8f8f8f',
        },
        neutral: {
          '1200': '#000200',
          '1100': '#071C04',
          '1000': '#0D3607',
          '900': '#14510B',
          '800': '#1A6B0E',
          '700': '#218612',
          '600': '#27a015',
          '500': '#46AE36',
          '400': '#64BB57',
          '300': '#83C879',
          '200': '#A1D69A',
          '150': '#C0E3BB',
          '100': '#DFF1DC',
        },
        yellow: {
          '1200': '#191706',
          '1100': '#3F3A0E',
          '1000': '#655C16',
          '900': '#8B7F1E',
          '800': '#B1A227',
          '700': '#D7C42F',
          '600': '#fde737',
          '500': '#FDEB56',
          '400': '#FEEE75',
          '300': '#FEF294',
          '200': '#FEF6B3',
          '150': '#FFFAD2',
          '100': '#FFFDF1',
        },
        magenta: {
          '1200': '#7A2236',
          '1100': '#8B263E',
          '1000': '#9D2B45',
          '900': '#AE304D',
          '800': '#C03555',
          '700': '#D1395D',
          '600': '#E33E64',
          '500': '#f4436c',
          '400': '#F65E81',
          '300': '#F77A97',
          '200': '#F995AC',
          '150': '#FAB0C1',
          '100': '#FCCBD7',
        },
        pink: {
          '100': '#ffe5ef',
          '150': '#ffe5ef',
          '200': '#f9acca',
          '300': '#ff5999',
          '400': '#ce2365',
          '500': '#931244',
          '600': '#f9acca',
          '700': '#ff5999',
          '800': '#ce2365',
          '900': '#931244',
          '1000': '#f9acca',
          '1100': '#ff5999',
          '1200': '#ce2365',
        },
        red: colors.red,
        blue: {
          '100': '#e4fcf8',
          '150': '#e4fcf8',
          '200': '#c3fcf3',
          '300': '#93dafc',
          '400': '#6dada3',
          '500': '#3c6c65',
          '600': '#e4fcf8',
          '700': '#c3fcf3',
          '800': '#93dafc',
          '900': '#6dada3',
          '1000': '#3c6c65',
          '1100': '#e4fcf8',
          '1200': '#c3fcf3',
        },
        aquamarine: {
          '100': '#a6fcf1',
          '150': '#a6fcf1',
          '200': '#49d6c3',
          '300': '#00917e',
          '400': '#026356',
          '500': '#023e36',
          '600': '#a6fcf1',
          '700': '#49d6c3',
          '800': '#00917e',
          '900': '#026356',
          '1000': '#023e36',
          '1100': '#a6fcf1',
          '1200': '#49d6c3',
        },
        orange: {
          '100': '#ffead4',
          '150': '#ffead4',
          '200': '#ffbc79',
          '300': '#fd8004',
          '400': '#a05103',
          '500': '#633303',
          '600': '#ffbc79',
          '700': '#fd8004',
          '800': '#a05103',
          '900': '#633303',
          '1000': '#ffbc79',
          '1100': '#fd8004',
          '1200': '#a05103',
        },
        // Add more as needed
      },
      foundations: {
        black: '#000000',
        white: '#ffffff',
      },
    },
    font: {
      family: defaultFamily,
      height: defaultHeight,
      spacing: defaultSpacing,
      paragraphSpacing: defaultParagraphSpacing,
      size: defaultHeight,
      weight: defaultWeight,
    },
    size: {
      dimension: defaultDimensions,
    },
  },
  color: {
    primary: 'nioGreen',
    secondary: 'magenta',
    accent: 'aquamarine',
    error: 'red',
    information: 'blue',
    success: 'nioGreen',
    warning: 'yellow',
    'neutral-dark': 'black',
    'neutral-light': 'black',
  },
  font: {
    family: {
      body: 'content',
      bodyShort: 'content',
      bodyLong: 'content',
      label: 'content',
      labelLong: 'content',
      h1: 'headline',
      h2: 'headline',
      h3: 'headline',
      h4: 'headline',
      h5: 'headline',
      h6: 'headline',
      hyperlink: 'content',
      hyperlinkHover: 'content',
      caption: 'content',
    },
    spacing: {
      hyperlink: 'base',
      hyperlinkHover: 'base',
      body: 'base',
      bodyShort: 'md',
      bodyLong: 'base',
      label: 'md',
      labelLong: 'md',
      h1: 'xs',
      h2: 'xs',
      h3: 'xs',
      h4: 'xs',
      h5: 'xs',
      h6: 'xs',
      caption: 'xs',
    },
    height: {
      hyperlink: 'sm',
      hyperlinkHover: 'sm',
      bodyShort: 'xs',
      body: 'sm',
      bodyLong: 'base',
      label: 'sm',
      labelLong: 'base',
      h1: '4xl',
      h2: '3xl',
      h3: '2xl',
      h4: 'xl',
      h5: 'lg',
      h6: 'md',
      caption: 'xs',
    },
    size: {
      hyperlink: 'base',
      hyperlinkHover: 'base',
      bodyShort: 'xs',
      body: 'sm',
      bodyLong: 'base',
      label: 'base',
      labelLong: 'base',
      h1: '4xl',
      h2: '3xl',
      h3: '2xl',
      h4: 'xl',
      h5: 'lg',
      h6: 'md',
      caption: 'xs',
    },
    weight: {
      hyperlink: 'medium',
      hyperlinkHover: 'medium',
      bodyShort: 'regular',
      body: 'regular',
      bodyLong: 'regular',
      label: 'medium',
      labelLong: 'medium',
      h1: 'bold',
      h2: 'bold',
      h3: 'semiBold',
      h4: 'semiBold',
      h5: 'semiBold',
      h6: 'semiBold',
      caption: 'regular',
    },
    paragraphSpacing: {
      hyperlink: 'base',
      hyperlinkHover: 'base',
      bodyShort: 'base',
      body: 'base',
      bodyLong: 'base',
      label: 'base',
      labelLong: 'base',
      h1: 'base',
      h2: 'base',
      h3: 'base',
      h4: 'base',
      h5: 'base',
      h6: 'base',
      caption: 'base',
    },
  },
  size: {
    border: {
      width: {
        xs: 50,
        sm: 100,
        md: 150,
      },
      radius: {
        none: 0,
        '3xs': 50,
        '2xs': 100,
        xs: 150,
        sm: 200,
        md: 300,
        lg: 400,
        xl: 500,
        '2xl': 600,
        '3xl': 700,
        '4xl': 800,
        pill: 1900,
      },
    },
    spacing: {
      '4xs': 50,
      '3xs': 100,
      '2xs': 200,
      xs: 300,
      sm: 400,
      md: 500,
      lg: 600,
      xl: 800,
      '2xl': 1000,
      '3xl': 1100,
      '4xl': 1300,
    },
  },
  palette: {
    dark: {
      surface: {
        'primary-default': { color: 'primary', scale: 400 },
        'primary-defaultHover': { color: 'primary', scale: 300 },
        'primary-defaultSubtle': { color: 'primary', scale: 900 },
        'primary-defaultSubtleHover': { color: 'primary', scale: 1000 },
        'primary-defaultSubtleHoverAlt': { color: 'primary', scale: 1100 },
        'secondary-default': { color: 'secondary', scale: 500 },
        'secondary-defaultHover': { color: 'secondary', scale: 400 },
        'secondary-defaultSubtle': { color: 'secondary', scale: 700 },
        'secondary-defaultSubtleHover': { color: 'secondary', scale: 800 },
        'disabled-default': { color: 'neutral-dark', scale: 600 },
        'error-default': { color: 'error', scale: 700 },
        'error-defaultHover': { color: 'error', scale: 800 },
        'error-defaultSubtle': { color: 'error', scale: 900 },
        'error-defaultSubtleHover': { color: 'error', scale: 1000 },
        'success-default': { color: 'success', scale: 700 },
        'success-defaultHover': { color: 'success', scale: 800 },
        'success-defaultSubtle': { color: 'success', scale: 900 },
        'success-defaultSubtleHover': { color: 'success', scale: 1000 },
        'information-default': { color: 'information', scale: 700 },
        'information-defaultHover': { color: 'information', scale: 800 },
        'information-defaultSubtle': { color: 'information', scale: 900 },
        'information-defaultSubtleHover': { color: 'information', scale: 1000 },
        'warning-default': { color: 'warning', scale: 700 },
        'warning-defaultHover': { color: 'warning', scale: 800 },
        'warning-defaultSubtle': { color: 'warning', scale: 900 },
        'warning-defaultSubtleHover': { color: 'warning', scale: 1000 },
        default: { color: 'primary', scale: 1200 },
        page: { color: 'primary', scale: 1100 },
        pageAlternative: { color: 'neutral-dark', scale: 1200 },
        alternative: { color: 'neutral-dark', scale: 1200 },
      },
      text: {
        'primary-onColor': { color: 'foundation.white' },
        'primary-onColorHover': { color: 'foundation.white' },
        'primary-onColorSubtle': { color: 'secondary', scale: 400 },
        'primary-onColorSubtleHover': { color: 'secondary', scale: 500 },
        'primary-default': { color: 'primary', scale: 400 },
        'primary-defaultHover': { color: 'primary', scale: 200 },
        'secondary-onColor': { color: 'foundation.white' },
        'secondary-onColorHover': { color: 'foundation.white' },
        'secondary-onColorSubtle': { color: 'error', scale: 300 },
        'secondary-onColorSubtleHover': { color: 'error', scale: 400 },
        'secondary-default': { color: 'secondary', scale: 100 },
        'secondary-defaultHover': { color: 'secondary', scale: 300 },
        'disabled-default': { color: 'neutral-light', scale: 300 },
        'disabled-onColor': { color: 'neutral-light', scale: 300 },
        'error-onColor': { color: 'error', scale: 400 },
        'error-onColorHover': { color: 'error', scale: 500 },
        'error-onColorSubtle': { color: 'error', scale: 300 },
        'error-onColorSubtleHover': { color: 'error', scale: 400 },
        'error-default': { color: 'error', scale: 300 },
        'error-defaultHover': { color: 'error', scale: 400 },
        'success-onColor': { color: 'success', scale: 400 },
        'success-onColorHover': { color: 'success', scale: 500 },
        'success-onColorSubtle': { color: 'success', scale: 300 },
        'success-onColorSubtleHover': { color: 'success', scale: 400 },
        'success-default': { color: 'success', scale: 300 },
        'success-defaultHover': { color: 'success', scale: 400 },
        'information-onColor': { color: 'information', scale: 400 },
        'information-onColorHover': { color: 'information', scale: 500 },
        'information-onColorSubtle': { color: 'information', scale: 300 },
        'information-onColorSubtleHover': { color: 'information', scale: 400 },
        'information-default': { color: 'information', scale: 300 },
        'information-defaultHover': { color: 'information', scale: 400 },
        'warning-onColor': { color: 'warning', scale: 400 },
        'warning-onColorHover': { color: 'warning', scale: 500 },
        'warning-onColorSubtle': { color: 'warning', scale: 300 },
        'warning-onColorSubtleHover': { color: 'warning', scale: 400 },
        'warning-default': { color: 'warning', scale: 300 },
        'warning-defaultHover': { color: 'warning', scale: 400 },
        'default-body': { color: 'foundation.white' },
        'default-hero': { color: 'foundation.white' },
        'default-heading': { color: 'foundation.white' },
        'default-caption': { color: 'secondary', scale: 400 },
        'default-placeholder': { color: 'secondary', scale: 400 },
        'onColor-hero': { color: 'foundation.white' },
        'onColor-heading': { color: 'foundation.white' },
        'onColor-body': { color: 'foundation.white' },
        'onColor-caption': { color: 'secondary', scale: 400 },
        'onColor-placeholder': { color: 'secondary', scale: 400 },
        'accent-default': { color: 'accent', scale: 200 },
        'accent-defaultHover': { color: 'accent', scale: 100 },
        'accent-onColor': { color: 'accent', scale: 400 },
        'accent-onColorHover': { color: 'accent', scale: 500 },
        'accent-onColorSubtle': { color: 'accent', scale: 200 },
        'accent-onColorSubtleHover': { color: 'accent', scale: 400 },
      },
      icon: {
        'primary-onColor': { color: 'foundation.white' },
        'primary-onColorHover': { color: 'foundation.white' },
        'primary-onColorSubtle': { color: 'secondary', scale: 400 },
        'primary-onColorSubtleHover': { color: 'secondary', scale: 500 },
        'primary-default': { color: 'foundation.white' },
        'primary-defaultHover': { color: 'foundation.white' },
        'primary-defaultSubtle': { color: 'foundation.white' },
        'primary-defaultSubtleHover': { color: 'foundation.white' },
        'secondary-onColor': { color: 'foundation.white' },
        'secondary-onColorHover': { color: 'foundation.white' },
        'secondary-onColorSubtle': { color: 'error', scale: 300 },
        'secondary-onColorSubtleHover': { color: 'error', scale: 400 },
        'secondary-default': { color: 'secondary', scale: 100 },
        'secondary-defaultHover': { color: 'secondary', scale: 300 },
        'disabled-default': { color: 'neutral-light', scale: 300 },
        'disabled-onColor': { color: 'neutral-light', scale: 300 },
        'error-onColor': { color: 'error', scale: 400 },
        'error-onColorHover': { color: 'error', scale: 500 },
        'error-onColorSubtle': { color: 'error', scale: 300 },
        'error-onColorSubtleHover': { color: 'error', scale: 400 },
        'error-default': { color: 'error', scale: 300 },
        'error-defaultHover': { color: 'error', scale: 400 },
        'success-onColor': { color: 'success', scale: 400 },
        'success-onColorHover': { color: 'success', scale: 500 },
        'success-onColorSubtle': { color: 'success', scale: 300 },
        'success-onColorSubtleHover': { color: 'success', scale: 400 },
        'success-default': { color: 'success', scale: 300 },
        'success-defaultHover': { color: 'success', scale: 400 },
        'information-onColor': { color: 'information', scale: 400 },
        'information-onColorHover': { color: 'information', scale: 500 },
        'information-onColorSubtle': { color: 'information', scale: 300 },
        'information-onColorSubtleHover': { color: 'information', scale: 400 },
        'information-default': { color: 'information', scale: 300 },
        'information-defaultHover': { color: 'information', scale: 400 },
        'warning-onColor': { color: 'warning', scale: 400 },
        'warning-onColorHover': { color: 'warning', scale: 500 },
        'warning-onColorSubtle': { color: 'warning', scale: 300 },
        'warning-onColorSubtleHover': { color: 'warning', scale: 400 },
        'warning-default': { color: 'warning', scale: 300 },
        'warning-defaultHover': { color: 'warning', scale: 400 },
      },
      border: {
        'primary-default': { color: 'primary', scale: 900 },
        'primary-defaultHover': { color: 'primary', scale: 800 },
        'primary-defaultSubtle': { color: 'primary', scale: 700 },
        'primary-defaultSubtleHover': { color: 'primary', scale: 600 },
        'primary-focus': { color: 'primary', scale: 900 },
        'error-default': { color: 'error', scale: 900 },
        'error-defaultHover': { color: 'error', scale: 800 },
        'error-defaultSubtle': { color: 'error', scale: 700 },
        'error-defaultSubtleHover': { color: 'error', scale: 600 },
        'error-focus': { color: 'error', scale: 900 },
        'success-default': { color: 'success', scale: 900 },
        'success-defaultHover': { color: 'success', scale: 800 },
        'success-defaultSubtle': { color: 'success', scale: 700 },
        'success-defaultSubtleHover': { color: 'success', scale: 600 },
        'success-focus': { color: 'success', scale: 900 },
        'information-default': { color: 'information', scale: 900 },
        'information-defaultHover': { color: 'information', scale: 800 },
        'information-defaultSubtle': { color: 'information', scale: 700 },
        'information-defaultSubtleHover': { color: 'information', scale: 600 },
        'information-focus': { color: 'information', scale: 900 },
        'warning-default': { color: 'warning', scale: 900 },
        'warning-defaultHover': { color: 'warning', scale: 800 },
        'warning-defaultSubtle': { color: 'warning', scale: 700 },
        'warning-defaultSubtleHover': { color: 'warning', scale: 600 },
        'warning-focus': { color: 'warning', scale: 900 },
        'secondary-default': { color: 'secondary', scale: 900 },
        'secondary-defaultHover': { color: 'secondary', scale: 800 },
        'secondary-defaultSubtle': { color: 'secondary', scale: 700 },
        'secondary-defaultSubtleHover': { color: 'secondary', scale: 600 },
        'secondary-focus': { color: 'secondary', scale: 900 },
        disabled: { color: 'neutral-light', scale: 1000 },
        'disabled-onColor': { color: 'neutral-light', scale: 200 },
        default: { color: 'neutral-dark', scale: 600 },
        'default-onColor': { color: 'neutral-light', scale: 800 },
      },
    },
    light: {
      surface: {
        'primary-default': { color: 'primary', scale: 500 },
        'primary-defaultHover': { color: 'primary', scale: 400 },
        'primary-defaultSubtle': { color: 'primary', scale: 100 },
        'primary-defaultSubtleHover': { color: 'primary', scale: 200 },
        'primary-defaultSubtleHoverAlt': { color: 'primary', scale: 200 },
        'secondary-default': { color: 'secondary', scale: 600 },
        'secondary-defaultHover': { color: 'secondary', scale: 700 },
        'secondary-defaultSubtle': { color: 'secondary', scale: 100 },
        'secondary-defaultSubtleHover': { color: 'secondary', scale: 200 },
        'disabled-default': { color: 'neutral-dark', scale: 500 },
        'error-default': { color: 'error', scale: 200 },
        'error-defaultHover': { color: 'error', scale: 300 },
        'error-defaultSubtle': { color: 'error', scale: 100 },
        'error-defaultSubtleHover': { color: 'error', scale: 150 },
        'success-default': { color: 'success', scale: 200 },
        'success-defaultHover': { color: 'success', scale: 300 },
        'success-defaultSubtle': { color: 'success', scale: 100 },
        'success-defaultSubtleHover': { color: 'success', scale: 150 },
        'information-default': { color: 'information', scale: 200 },
        'information-defaultHover': { color: 'information', scale: 300 },
        'information-defaultSubtle': { color: 'information', scale: 100 },
        'information-defaultSubtleHover': { color: 'information', scale: 150 },
        'warning-default': { color: 'warning', scale: 200 },
        'warning-defaultHover': { color: 'warning', scale: 300 },
        'warning-defaultSubtle': { color: 'warning', scale: 100 },
        'warning-defaultSubtleHover': { color: 'warning', scale: 150 },
        default: { color: 'foundation.white' },
        page: { color: 'foundation.white' },
        pageAlternative: { color: 'neutral-light', scale: 1100 },
        alternative: { color: 'neutral-light', scale: 100 },
      },
      text: {
        'primary-onColor': { color: 'foundation.white' },
        'primary-onColorHover': { color: 'foundation.white' },
        'primary-onColorSubtle': { color: 'primary', scale: 900 },
        'primary-onColorSubtleHover': { color: 'primary', scale: 1000 },
        'primary-default': { color: 'primary', scale: 500 },
        'primary-defaultHover': { color: 'primary', scale: 400 },
        'secondary-onColor': { color: 'foundation.white' },
        'secondary-onColorHover': { color: 'foundation.white' },
        'secondary-onColorSubtle': { color: 'secondary', scale: 800 },
        'secondary-onColorSubtleHover': { color: 'secondary', scale: 900 },
        'secondary-default': { color: 'secondary', scale: 900 },
        'secondary-defaultHover': { color: 'secondary', scale: 800 },
        'disabled-default': { color: 'neutral-dark', scale: 400 },
        'disabled-onColor': { color: 'foundation.white' },
        'error-onColor': { color: 'neutral-light', scale: 100 },
        'error-onColorHover': { color: 'neutral-light', scale: 200 },
        'error-onColorSubtle': { color: 'error', scale: 700 },
        'error-onColorSubtleHover': { color: 'error', scale: 800 },
        'error-default': { color: 'error', scale: 800 },
        'error-defaultHover': { color: 'error', scale: 900 },
        'success-onColor': { color: 'neutral-light', scale: 100 },
        'success-onColorHover': { color: 'neutral-light', scale: 200 },
        'success-onColorSubtle': { color: 'success', scale: 800 },
        'success-onColorSubtleHover': { color: 'success', scale: 900 },
        'success-default': { color: 'success', scale: 800 },
        'success-defaultHover': { color: 'success', scale: 900 },
        'information-onColor': { color: 'neutral-light', scale: 100 },
        'information-onColorHover': { color: 'neutral-light', scale: 200 },
        'information-onColorSubtle': { color: 'information', scale: 800 },
        'information-onColorSubtleHover': { color: 'information', scale: 900 },
        'information-default': { color: 'information', scale: 800 },
        'information-defaultHover': { color: 'information', scale: 900 },
        'warning-onColor': { color: 'neutral-light', scale: 100 },
        'warning-onColorHover': { color: 'neutral-light', scale: 200 },
        'warning-onColorSubtle': { color: 'warning', scale: 800 },
        'warning-onColorSubtleHover': { color: 'warning', scale: 900 },
        'warning-default': { color: 'warning', scale: 800 },
        'warning-defaultHover': { color: 'warning', scale: 900 },
        'default-body': { color: 'neutral-dark', scale: 600 },
        'default-hero': { color: 'neutral-dark', scale: 1100 },
        'default-heading': { color: 'neutral-dark', scale: 1100 },
        'default-caption': { color: 'neutral-dark', scale: 700 },
        'default-placeholder': { color: 'neutral-dark', scale: 700 },
        'onColor-hero': { color: 'neutral-light', scale: 100 },
        'onColor-heading': { color: 'neutral-light', scale: 100 },
        'onColor-body': { color: 'neutral-light', scale: 100 },
        'onColor-caption': { color: 'neutral-light', scale: 200 },
        'onColor-placeholder': { color: 'neutral-light', scale: 300 },
        'accent-onColor': { color: 'neutral-light', scale: 100 },
        'accent-onColorHover': { color: 'neutral-light', scale: 200 },
        'accent-onColorSubtle': { color: 'accent', scale: 300 },
        'accent-onColorSubtleHover': { color: 'accent', scale: 300 },
        'accent-default': { color: 'accent', scale: 200 },
        'accent-defaultHover': { color: 'accent', scale: 200 },
      },
      icon: {
        'primary-onColor': { color: 'primary', scale: 100 },
        'primary-onColorHover': { color: 'primary', scale: 200 },
        'primary-onColorSubtle': { color: 'primary', scale: 900 },
        'primary-onColorSubtleHover': { color: 'primary', scale: 1000 },
        'primary-default': { color: 'primary', scale: 400 },
        'primary-defaultHover': { color: 'primary', scale: 900 },
        'primary-defaultSubtle': { color: 'primary', scale: 800 },
        'primary-defaultSubtleHover': { color: 'primary', scale: 900 },
        'secondary-onColor': { color: 'secondary', scale: 800 },
        'secondary-onColorHover': { color: 'secondary', scale: 900 },
        'secondary-onColorSubtle': { color: 'secondary', scale: 800 },
        'secondary-onColorSubtleHover': { color: 'secondary', scale: 900 },
        'secondary-default': { color: 'secondary', scale: 800 },
        'secondary-defaultHover': { color: 'secondary', scale: 900 },
        'disabled-default': { color: 'neutral-dark', scale: 600 },
        'disabled-onColor': { color: 'foundation.white' },
        'error-onColor': { color: 'neutral-light', scale: 100 },
        'error-onColorHover': { color: 'neutral-light', scale: 200 },
        'error-onColorSubtle': { color: 'error', scale: 700 },
        'error-onColorSubtleHover': { color: 'error', scale: 800 },
        'error-default': { color: 'error', scale: 800 },
        'error-defaultHover': { color: 'error', scale: 900 },
        'success-onColor': { color: 'neutral-light', scale: 100 },
        'success-onColorHover': { color: 'neutral-light', scale: 200 },
        'success-onColorSubtle': { color: 'success', scale: 800 },
        'success-onColorSubtleHover': { color: 'success', scale: 900 },
        'success-default': { color: 'success', scale: 800 },
        'success-defaultHover': { color: 'success', scale: 900 },
        'information-onColor': { color: 'neutral-light', scale: 100 },
        'information-onColorHover': { color: 'neutral-light', scale: 200 },
        'information-onColorSubtle': { color: 'information', scale: 800 },
        'information-onColorSubtleHover': { color: 'information', scale: 900 },
        'information-default': { color: 'information', scale: 800 },
        'information-defaultHover': { color: 'information', scale: 900 },
        'warning-onColor': { color: 'neutral-light', scale: 100 },
        'warning-onColorHover': { color: 'neutral-light', scale: 200 },
        'warning-onColorSubtle': { color: 'warning', scale: 800 },
        'warning-onColorSubtleHover': { color: 'warning', scale: 900 },
        'warning-default': { color: 'warning', scale: 800 },
        'warning-defaultHover': { color: 'warning', scale: 900 },
      },
      border: {
        'primary-default': { color: 'primary', scale: 500 },
        'primary-defaultHover': { color: 'primary', scale: 400 },
        'primary-defaultSubtle': { color: 'primary', scale: 400 },
        'primary-defaultSubtleHover': { color: 'primary', scale: 500 },
        'primary-focus': { color: 'primary', scale: 900 },
        'error-default': { color: 'error', scale: 800 },
        'error-defaultHover': { color: 'error', scale: 900 },
        'error-defaultSubtle': { color: 'error', scale: 150 },
        'error-defaultSubtleHover': { color: 'error', scale: 300 },
        'error-focus': { color: 'error', scale: 800 },
        'success-default': { color: 'success', scale: 800 },
        'success-defaultHover': { color: 'success', scale: 900 },
        'success-defaultSubtle': { color: 'success', scale: 150 },
        'success-defaultSubtleHover': { color: 'success', scale: 300 },
        'success-focus': { color: 'success', scale: 800 },
        'warning-default': { color: 'warning', scale: 800 },
        'warning-defaultHover': { color: 'warning', scale: 900 },
        'warning-defaultSubtle': { color: 'warning', scale: 150 },
        'warning-defaultSubtleHover': { color: 'warning', scale: 300 },
        'warning-focus': { color: 'warning', scale: 800 },
        'information-default': { color: 'information', scale: 800 },
        'information-defaultHover': { color: 'information', scale: 900 },
        'information-defaultSubtle': { color: 'information', scale: 150 },
        'information-defaultSubtleHover': { color: 'information', scale: 300 },
        'information-focus': { color: 'information', scale: 800 },
        'secondary-default': { color: 'secondary', scale: 800 },
        'secondary-defaultHover': { color: 'secondary', scale: 900 },
        'secondary-defaultSubtle': { color: 'secondary', scale: 300 },
        'secondary-defaultSubtleHover': { color: 'secondary', scale: 500 },
        'secondary-focus': { color: 'secondary', scale: 900 },
        disabled: { color: 'neutral-light', scale: 200 },
        'disabled-onColor': { color: 'neutral-light', scale: 900 },
        default: { color: 'neutral-light', scale: 200 },
        'default-onColor': { color: 'neutral-light', scale: 200 },
      },
    },
  },
}
