import { colors, type Theme } from 'theme-token-manager'

export const telcelTheme: Theme = {
  id: 'default',
  name: 'default',
  base: {
    color: {
      collection: {
        'deep-blue': colors.deepBlue,
        'galaxy-purple': colors.galaxyPurple,
        green: colors.green,
        red: colors.red,
        yellow: colors.yellow,
        slate: colors.slate,
        grey: colors.grey,
        pink: colors.pink,
      },
      foundations: {
        black: colors.black,
        white: colors.white,
      },
    },
    font: {
      family: {
        headline: 'Inter',
        content: 'Inter',
      },
      height: {
        '4xl': 66,
        '3xl': 50,
        '2xl': 42,
        xl: 34,
        lg: 26,
        md: 22,
        base: 18,
        sm: 16,
        xs: 14,
      },
      spacing: {
        lg: 0,
        md: 0,
        xs: 0,
        base: 0,
      },
      paragraphSpacing: {
        base: 16,
      },
      size: {
        '4xl': 64,
        '3xl': 48,
        '2xl': 40,
        xl: 32,
        lg: 24,
        md: 20,
        base: 16,
        sm: 14,
        xs: 12,
      },
      weight: {
        regular: 400,
        medium: 500,
        semiBold: 600,
        bold: 700,
      },
    },
    size: {
      dimension: {
        '0': 0,
        '25': 1,
        '50': 2,
        '100': 4,
        '150': 6,
        '200': 8,
        '300': 12,
        '400': 16,
        '500': 20,
        '600': 24,
        '700': 28,
        '800': 32,
        '900': 36,
        '1000': 40,
        '1100': 48,
        '1200': 56,
        '1300': 64,
        '1400': 72,
        '1500': 96,
        '1600': 128,
        '1700': 256,
        '1800': 512,
        '1900': 1024,
      },
    },
  },
  color: {
    primary: 'deep-blue',
    secondary: 'pink',
    accent: 'galaxy-purple',
    error: 'red',
    information: 'deep-blue',
    success: 'green',
    warning: 'yellow',
    'neutral-dark': 'slate',
    'neutral-light': 'grey',
  },
  font: {
    family: {
      body: 'content',
      bodyShort: 'content',
      bodyLong: 'content',
      label: 'content',
      labelLong: 'content',
      h1: 'headline',
      h2: 'headline',
      h3: 'headline',
      h4: 'headline',
      h5: 'headline',
      h6: 'headline',
      hyperlink: 'content',
      hyperlinkHover: 'content',
      caption: 'content',
    },
    spacing: {
      hyperlink: 'base',
      hyperlinkHover: 'base',
      body: 'base',
      bodyShort: 'md',
      bodyLong: 'base',
      label: 'md',
      labelLong: 'md',
      h1: 'xs',
      h2: 'xs',
      h3: 'xs',
      h4: 'xs',
      h5: 'xs',
      h6: 'xs',
      caption: 'xs',
    },
    height: {
      hyperlink: 'xs',
      hyperlinkHover: 'xs',
      bodyShort: 'xs',
      body: 'sm',
      bodyLong: 'base',
      label: 'sm',
      labelLong: 'base',
      h1: '4xl',
      h2: '3xl',
      h3: '2xl',
      h4: 'xl',
      h5: 'lg',
      h6: 'md',
      caption: 'xs',
    },
    size: {
      hyperlink: 'base',
      hyperlinkHover: 'base',
      bodyShort: 'base',
      body: 'sm',
      bodyLong: 'base',
      label: 'base',
      labelLong: 'base',
      h1: '4xl',
      h2: '3xl',
      h3: '2xl',
      h4: 'xl',
      h5: 'lg',
      h6: 'md',
      caption: 'xs',
    },
    weight: {
      hyperlink: 'regular',
      hyperlinkHover: 'regular',
      bodyShort: 'regular',
      body: 'regular',
      bodyLong: 'regular',
      label: 'regular',
      labelLong: 'regular',
      h1: 'bold',
      h2: 'bold',
      h3: 'semiBold',
      h4: 'semiBold',
      h5: 'semiBold',
      h6: 'semiBold',
      caption: 'medium',
    },
    paragraphSpacing: {
      hyperlink: 'base',
      hyperlinkHover: 'base',
      bodyShort: 'base',
      body: 'base',
      bodyLong: 'base',
      label: 'base',
      labelLong: 'base',
      h1: 'base',
      h2: 'base',
      h3: 'base',
      h4: 'base',
      h5: 'base',
      h6: 'base',
      caption: 'base',
    },
  },
  size: {
    border: {
      width: {
        xs: 25,
        sm: 50,
        md: 100,
      },
      radius: {
        none: 0,
        '3xs': 50,
        '2xs': 100,
        xs: 150,
        sm: 200,
        md: 300,
        lg: 400,
        xl: 500,
        '2xl': 600,
        '3xl': 700,
        '4xl': 800,
        pill: 1900,
      },
    },
    spacing: {
      '4xs': 50,
      '3xs': 100,
      '2xs': 200,
      xs: 300,
      sm: 400,
      md: 500,
      lg: 600,
      xl: 800,
      '2xl': 1000,
      '3xl': 1100,
      '4xl': 1300,
    },
  },
  palette: {
    dark: {
      surface: {
        'primary-default': { color: 'primary', scale: 700 },
        'primary-defaultHover': { color: 'primary', scale: 900 },
        'primary-defaultSubtle': { color: 'neutral-light', scale: 900 },
        'primary-defaultSubtleHover': { color: 'neutral-light', scale: 800 },
        'primary-defaultSubtleHoverAlt': { color: 'neutral-light', scale: 900 },
        'secondary-default': { color: 'secondary', scale: 700 },
        'secondary-defaultHover': { color: 'secondary', scale: 900 },
        'secondary-defaultSubtle': { color: 'neutral-dark', scale: 1000 },
        'secondary-defaultSubtleHover': { color: 'neutral-dark', scale: 1000 },
        'disabled-default': { color: 'neutral-dark', scale: 800 },
        'error-default': { color: 'error', scale: 300 },
        'error-defaultHover': { color: 'error', scale: 400 },
        'error-defaultSubtle': { color: 'error', scale: 900 },
        'error-defaultSubtleHover': { color: 'error', scale: 1000 },
        'success-default': { color: 'success', scale: 400 },
        'success-defaultHover': { color: 'success', scale: 500 },
        'success-defaultSubtle': { color: 'success', scale: 900 },
        'success-defaultSubtleHover': { color: 'success', scale: 1000 },
        'information-default': { color: 'information', scale: 300 },
        'information-defaultHover': { color: 'information', scale: 400 },
        'information-defaultSubtle': { color: 'information', scale: 900 },
        'information-defaultSubtleHover': { color: 'information', scale: 1000 },
        'warning-default': { color: 'warning', scale: 400 },
        'warning-defaultHover': { color: 'warning', scale: 500 },
        'warning-defaultSubtle': { color: 'warning', scale: 900 },
        'warning-defaultSubtleHover': { color: 'warning', scale: 1000 },
        default: { color: 'neutral-dark', scale: 1100 },
        page: { color: 'neutral-dark', scale: 1100 },
        pageAlternative: { color: 'neutral-dark', scale: 1100 },
        alternative: { color: 'neutral-dark', scale: 1100 },
      },
      text: {
        'primary-onColor': { color: 'foundation.white' },
        'primary-onColorHover': { color: 'foundation.white' },
        'primary-onColorSubtle': { color: 'primary', scale: 200 },
        'primary-onColorSubtleHover': { color: 'primary', scale: 300 },
        'primary-default': { color: 'primary', scale: 600 },
        'primary-defaultHover': { color: 'primary', scale: 300 },
        'secondary-onColor': { color: 'foundation.white' },
        'secondary-onColorHover': { color: 'foundation.white' },
        'secondary-onColorSubtle': { color: 'secondary', scale: 200 },
        'secondary-onColorSubtleHover': { color: 'secondary', scale: 300 },
        'secondary-default': { color: 'secondary', scale: 200 },
        'secondary-defaultHover': { color: 'secondary', scale: 300 },
        'disabled-default': { color: 'neutral-light', scale: 300 },
        'disabled-onColor': { color: 'foundation.white' },
        'error-onColor': { color: 'neutral-light', scale: 900 },
        'error-onColorHover': { color: 'neutral-light', scale: 1100 },
        'error-onColorSubtle': { color: 'error', scale: 300 },
        'error-onColorSubtleHover': { color: 'error', scale: 400 },
        'error-default': { color: 'error', scale: 300 },
        'error-defaultHover': { color: 'error', scale: 400 },
        'success-onColor': { color: 'neutral-light', scale: 900 },
        'success-onColorHover': { color: 'neutral-light', scale: 1100 },
        'success-onColorSubtle': { color: 'success', scale: 300 },
        'success-onColorSubtleHover': { color: 'success', scale: 400 },
        'success-default': { color: 'success', scale: 300 },
        'success-defaultHover': { color: 'success', scale: 400 },
        'information-onColor': { color: 'neutral-dark', scale: 900 },
        'information-onColorHover': { color: 'neutral-dark', scale: 1100 },
        'information-onColorSubtle': { color: 'information', scale: 300 },
        'information-onColorSubtleHover': { color: 'information', scale: 400 },
        'information-default': { color: 'information', scale: 300 },
        'information-defaultHover': { color: 'information', scale: 400 },
        'warning-onColor': { color: 'neutral-dark', scale: 900 },
        'warning-onColorHover': { color: 'neutral-dark', scale: 1100 },
        'warning-onColorSubtle': { color: 'warning', scale: 300 },
        'warning-onColorSubtleHover': { color: 'warning', scale: 400 },
        'warning-default': { color: 'warning', scale: 300 },
        'warning-defaultHover': { color: 'warning', scale: 400 },
        'default-body': { color: 'neutral-dark', scale: 100 },
        'default-hero': { color: 'neutral-dark', scale: 200 },
        'default-heading': { color: 'neutral-dark', scale: 200 },
        'default-caption': { color: 'neutral-dark', scale: 300 },
        'default-placeholder': { color: 'neutral-dark', scale: 300 },
        'onColor-hero': { color: 'neutral-dark', scale: 1100 },
        'onColor-heading': { color: 'neutral-dark', scale: 1100 },
        'onColor-body': { color: 'neutral-dark', scale: 1000 },
        'onColor-caption': { color: 'neutral-dark', scale: 800 },
        'onColor-placeholder': { color: 'neutral-dark', scale: 700 },
        'accent-default': { color: 'accent', scale: 300 },
        'accent-defaultHover': { color: 'accent', scale: 400 },
        'accent-onColor': { color: 'neutral-dark', scale: 900 },
        'accent-onColorHover': { color: 'neutral-dark', scale: 1100 },
        'accent-onColorSubtle': { color: 'accent', scale: 300 },
        'accent-onColorSubtleHover': { color: 'accent', scale: 400 },
      },
      icon: {
        'primary-onColor': { color: 'primary', scale: 900 },
        'primary-onColorHover': { color: 'primary', scale: 1000 },
        'primary-onColorSubtle': { color: 'primary', scale: 200 },
        'primary-onColorSubtleHover': { color: 'primary', scale: 300 },
        'primary-default': { color: 'primary', scale: 400 },
        'primary-defaultHover': { color: 'primary', scale: 500 },
        'primary-defaultSubtle': { color: 'primary', scale: 400 },
        'primary-defaultSubtleHover': { color: 'primary', scale: 500 },
        'secondary-onColor': { color: 'secondary', scale: 300 },
        'secondary-onColorHover': { color: 'secondary', scale: 400 },
        'secondary-onColorSubtle': { color: 'secondary', scale: 300 },
        'secondary-onColorSubtleHover': { color: 'secondary', scale: 400 },
        'secondary-default': { color: 'secondary', scale: 300 },
        'secondary-defaultHover': { color: 'secondary', scale: 400 },
        'disabled-default': { color: 'neutral-light', scale: 300 },
        'disabled-onColor': { color: 'neutral-light', scale: 300 },
        'error-onColor': { color: 'neutral-light', scale: 1000 },
        'error-onColorHover': { color: 'neutral-light', scale: 800 },
        'error-onColorSubtle': { color: 'error', scale: 300 },
        'error-onColorSubtleHover': { color: 'error', scale: 400 },
        'error-default': { color: 'error', scale: 300 },
        'error-defaultHover': { color: 'error', scale: 400 },
        'success-onColor': { color: 'neutral-light', scale: 900 },
        'success-onColorHover': { color: 'neutral-light', scale: 800 },
        'success-onColorSubtle': { color: 'success', scale: 400 },
        'success-onColorSubtleHover': { color: 'success', scale: 300 },
        'success-default': { color: 'success', scale: 400 },
        'success-defaultHover': { color: 'success', scale: 500 },
        'information-onColor': { color: 'neutral-light', scale: 900 },
        'information-onColorHover': { color: 'neutral-light', scale: 1000 },
        'information-onColorSubtle': { color: 'information', scale: 400 },
        'information-onColorSubtleHover': { color: 'information', scale: 500 },
        'information-default': { color: 'information', scale: 400 },
        'information-defaultHover': { color: 'information', scale: 500 },
        'warning-onColor': { color: 'neutral-light', scale: 900 },
        'warning-onColorHover': { color: 'neutral-light', scale: 1000 },
        'warning-onColorSubtle': { color: 'warning', scale: 400 },
        'warning-onColorSubtleHover': { color: 'warning', scale: 500 },
        'warning-default': { color: 'warning', scale: 400 },
        'warning-defaultHover': { color: 'warning', scale: 500 },
      },
      border: {
        'primary-default': { color: 'primary', scale: 600 },
        'primary-defaultHover': { color: 'primary', scale: 400 },
        'primary-defaultSubtle': { color: 'primary', scale: 700 },
        'primary-defaultSubtleHover': { color: 'primary', scale: 800 },
        'primary-focus': { color: 'primary', scale: 300 },
        'error-default': { color: 'error', scale: 300 },
        'error-defaultHover': { color: 'error', scale: 400 },
        'error-defaultSubtle': { color: 'error', scale: 800 },
        'error-defaultSubtleHover': { color: 'error', scale: 900 },
        'error-focus': { color: 'error', scale: 300 },
        'success-default': { color: 'success', scale: 400 },
        'success-defaultHover': { color: 'success', scale: 500 },
        'success-defaultSubtle': { color: 'success', scale: 900 },
        'success-defaultSubtleHover': { color: 'success', scale: 1000 },
        'success-focus': { color: 'success', scale: 400 },
        'information-default': { color: 'information', scale: 400 },
        'information-defaultHover': { color: 'information', scale: 500 },
        'information-defaultSubtle': { color: 'information', scale: 900 },
        'information-defaultSubtleHover': { color: 'information', scale: 1000 },
        'information-focus': { color: 'information', scale: 400 },
        'warning-default': { color: 'warning', scale: 400 },
        'warning-defaultHover': { color: 'warning', scale: 500 },
        'warning-defaultSubtle': { color: 'warning', scale: 900 },
        'warning-defaultSubtleHover': { color: 'warning', scale: 1000 },
        'warning-focus': { color: 'warning', scale: 400 },
        'secondary-default': { color: 'secondary', scale: 800 },
        'secondary-defaultHover': { color: 'secondary', scale: 700 },
        'secondary-defaultSubtle': { color: 'secondary', scale: 800 },
        'secondary-defaultSubtleHover': { color: 'secondary', scale: 700 },
        'secondary-focus': { color: 'secondary', scale: 800 },
        disabled: { color: 'neutral-light', scale: 1000 },
        'disabled-onColor': { color: 'neutral-light', scale: 200 },
        default: { color: 'neutral-light', scale: 800 },
        'default-onColor': { color: 'neutral-light', scale: 800 },
      },
    },
    light: {
      surface: {
        'primary-default': { color: 'primary', scale: 700 },
        'primary-defaultHover': { color: 'primary', scale: 800 },
        'primary-defaultSubtle': { color: 'primary', scale: 100 },
        'primary-defaultSubtleHover': { color: 'primary', scale: 150 },
        'primary-defaultSubtleHoverAlt': { color: 'primary', scale: 150 },
        'secondary-default': { color: 'secondary', scale: 700 },
        'secondary-defaultHover': { color: 'secondary', scale: 900 },
        'secondary-defaultSubtle': { color: 'secondary', scale: 100 },
        'secondary-defaultSubtleHover': { color: 'secondary', scale: 150 },
        'disabled-default': { color: 'neutral-dark', scale: 500 },
        'error-default': { color: 'error', scale: 800 },
        'error-defaultHover': { color: 'error', scale: 900 },
        'error-defaultSubtle': { color: 'error', scale: 100 },
        'error-defaultSubtleHover': { color: 'error', scale: 150 },
        'success-default': { color: 'success', scale: 800 },
        'success-defaultHover': { color: 'success', scale: 900 },
        'success-defaultSubtle': { color: 'success', scale: 100 },
        'success-defaultSubtleHover': { color: 'success', scale: 150 },
        'information-default': { color: 'information', scale: 800 },
        'information-defaultHover': { color: 'information', scale: 900 },
        'information-defaultSubtle': { color: 'information', scale: 100 },
        'information-defaultSubtleHover': { color: 'information', scale: 150 },
        'warning-default': { color: 'warning', scale: 800 },
        'warning-defaultHover': { color: 'warning', scale: 900 },
        'warning-defaultSubtle': { color: 'warning', scale: 100 },
        'warning-defaultSubtleHover': { color: 'warning', scale: 150 },
        default: { color: 'foundation.white' },
        page: { color: 'foundation.white' },
        pageAlternative: { color: 'neutral-light', scale: 1100 },
        alternative: { color: 'neutral-light', scale: 100 },
      },
      text: {
        'primary-onColor': { color: 'primary', scale: 100 },
        'primary-onColorHover': { color: 'primary', scale: 200 },
        'primary-onColorSubtle': { color: 'primary', scale: 900 },
        'primary-onColorSubtleHover': { color: 'primary', scale: 1000 },
        'primary-default': { color: 'primary', scale: 800 },
        'primary-defaultHover': { color: 'primary', scale: 900 },
        'secondary-onColor': { color: 'secondary', scale: 100 },
        'secondary-onColorHover': { color: 'secondary', scale: 200 },
        'secondary-onColorSubtle': { color: 'secondary', scale: 900 },
        'secondary-onColorSubtleHover': { color: 'secondary', scale: 1000 },
        'secondary-default': { color: 'secondary', scale: 500 },
        'secondary-defaultHover': { color: 'secondary', scale: 900 },
        'disabled-default': { color: 'neutral-light', scale: 600 },
        'disabled-onColor': { color: 'foundation.white' },
        'error-onColor': { color: 'neutral-light', scale: 100 },
        'error-onColorHover': { color: 'neutral-light', scale: 200 },
        'error-onColorSubtle': { color: 'error', scale: 700 },
        'error-onColorSubtleHover': { color: 'error', scale: 800 },
        'error-default': { color: 'error', scale: 800 },
        'error-defaultHover': { color: 'error', scale: 900 },
        'success-onColor': { color: 'neutral-light', scale: 100 },
        'success-onColorHover': { color: 'neutral-light', scale: 200 },
        'success-onColorSubtle': { color: 'success', scale: 800 },
        'success-onColorSubtleHover': { color: 'success', scale: 900 },
        'success-default': { color: 'success', scale: 800 },
        'success-defaultHover': { color: 'success', scale: 900 },
        'information-onColor': { color: 'neutral-light', scale: 100 },
        'information-onColorHover': { color: 'neutral-light', scale: 200 },
        'information-onColorSubtle': { color: 'information', scale: 800 },
        'information-onColorSubtleHover': { color: 'information', scale: 900 },
        'information-default': { color: 'information', scale: 800 },
        'information-defaultHover': { color: 'information', scale: 900 },
        'warning-onColor': { color: 'neutral-light', scale: 100 },
        'warning-onColorHover': { color: 'neutral-light', scale: 200 },
        'warning-onColorSubtle': { color: 'warning', scale: 800 },
        'warning-onColorSubtleHover': { color: 'warning', scale: 900 },
        'warning-default': { color: 'warning', scale: 800 },
        'warning-defaultHover': { color: 'warning', scale: 900 },
        'default-body': { color: 'neutral-light', scale: 900 },
        'default-hero': { color: 'neutral-light', scale: 1100 },
        'default-heading': { color: 'neutral-light', scale: 1100 },
        'default-caption': { color: 'neutral-light', scale: 700 },
        'default-placeholder': { color: 'neutral-light', scale: 700 },
        'onColor-hero': { color: 'neutral-light', scale: 100 },
        'onColor-heading': { color: 'neutral-light', scale: 100 },
        'onColor-body': { color: 'neutral-light', scale: 100 },
        'onColor-caption': { color: 'neutral-light', scale: 200 },
        'onColor-placeholder': { color: 'neutral-light', scale: 300 },
        'accent-onColor': { color: 'neutral-light', scale: 100 },
        'accent-onColorHover': { color: 'neutral-light', scale: 200 },
        'accent-onColorSubtle': { color: 'accent', scale: 800 },
        'accent-onColorSubtleHover': { color: 'accent', scale: 900 },
        'accent-default': { color: 'accent', scale: 800 },
        'accent-defaultHover': { color: 'accent', scale: 900 },
      },
      icon: {
        'primary-onColor': { color: 'primary', scale: 100 },
        'primary-onColorHover': { color: 'primary', scale: 200 },
        'primary-onColorSubtle': { color: 'primary', scale: 900 },
        'primary-onColorSubtleHover': { color: 'primary', scale: 1000 },
        'primary-default': { color: 'primary', scale: 800 },
        'primary-defaultHover': { color: 'primary', scale: 900 },
        'primary-defaultSubtle': { color: 'primary', scale: 500 },
        'primary-defaultSubtleHover': { color: 'primary', scale: 600 },
        'secondary-onColor': { color: 'secondary', scale: 800 },
        'secondary-onColorHover': { color: 'secondary', scale: 900 },
        'secondary-onColorSubtle': { color: 'secondary', scale: 800 },
        'secondary-onColorSubtleHover': { color: 'secondary', scale: 900 },
        'secondary-default': { color: 'secondary', scale: 800 },
        'secondary-defaultHover': { color: 'secondary', scale: 900 },
        'disabled-default': { color: 'neutral-light', scale: 600 },
        'disabled-onColor': { color: 'neutral-light', scale: 600 },
        'error-onColor': { color: 'neutral-light', scale: 100 },
        'error-onColorHover': { color: 'neutral-light', scale: 200 },
        'error-onColorSubtle': { color: 'error', scale: 700 },
        'error-onColorSubtleHover': { color: 'error', scale: 800 },
        'error-default': { color: 'error', scale: 800 },
        'error-defaultHover': { color: 'error', scale: 900 },
        'success-onColor': { color: 'neutral-light', scale: 100 },
        'success-onColorHover': { color: 'neutral-light', scale: 200 },
        'success-onColorSubtle': { color: 'success', scale: 800 },
        'success-onColorSubtleHover': { color: 'success', scale: 900 },
        'success-default': { color: 'success', scale: 800 },
        'success-defaultHover': { color: 'success', scale: 900 },
        'information-onColor': { color: 'neutral-light', scale: 100 },
        'information-onColorHover': { color: 'neutral-light', scale: 200 },
        'information-onColorSubtle': { color: 'information', scale: 800 },
        'information-onColorSubtleHover': { color: 'information', scale: 900 },
        'information-default': { color: 'information', scale: 800 },
        'information-defaultHover': { color: 'information', scale: 900 },
        'warning-onColor': { color: 'neutral-light', scale: 100 },
        'warning-onColorHover': { color: 'neutral-light', scale: 200 },
        'warning-onColorSubtle': { color: 'warning', scale: 800 },
        'warning-onColorSubtleHover': { color: 'warning', scale: 900 },
        'warning-default': { color: 'warning', scale: 800 },
        'warning-defaultHover': { color: 'warning', scale: 900 },
      },
      border: {
        'primary-default': { color: 'primary', scale: 800 },
        'primary-defaultHover': { color: 'primary', scale: 900 },
        'primary-defaultSubtle': { color: 'primary', scale: 300 },
        'primary-defaultSubtleHover': { color: 'primary', scale: 500 },
        'primary-focus': { color: 'primary', scale: 900 },
        'error-default': { color: 'error', scale: 800 },
        'error-defaultHover': { color: 'error', scale: 900 },
        'error-defaultSubtle': { color: 'error', scale: 150 },
        'error-defaultSubtleHover': { color: 'error', scale: 300 },
        'error-focus': { color: 'error', scale: 800 },
        'success-default': { color: 'success', scale: 800 },
        'success-defaultHover': { color: 'success', scale: 900 },
        'success-defaultSubtle': { color: 'success', scale: 150 },
        'success-defaultSubtleHover': { color: 'success', scale: 300 },
        'success-focus': { color: 'success', scale: 800 },
        'warning-default': { color: 'warning', scale: 800 },
        'warning-defaultHover': { color: 'warning', scale: 900 },
        'warning-defaultSubtle': { color: 'warning', scale: 150 },
        'warning-defaultSubtleHover': { color: 'warning', scale: 300 },
        'warning-focus': { color: 'warning', scale: 800 },
        'information-default': { color: 'information', scale: 800 },
        'information-defaultHover': { color: 'information', scale: 900 },
        'information-defaultSubtle': { color: 'information', scale: 150 },
        'information-defaultSubtleHover': { color: 'information', scale: 300 },
        'information-focus': { color: 'information', scale: 800 },
        'secondary-default': { color: 'secondary', scale: 800 },
        'secondary-defaultHover': { color: 'secondary', scale: 900 },
        'secondary-defaultSubtle': { color: 'secondary', scale: 300 },
        'secondary-defaultSubtleHover': { color: 'secondary', scale: 500 },
        'secondary-focus': { color: 'secondary', scale: 900 },
        disabled: { color: 'neutral-light', scale: 200 },
        'disabled-onColor': { color: 'neutral-light', scale: 900 },
        default: { color: 'neutral-light', scale: 300 },
        'default-onColor': { color: 'foundation.white' },
      },
    },
  },
}
