import {
  BorderRadiusValues,
  BorderWidthValues,
  ColorScaleStringValues,
  ColorScaleValues,
  DimensionValues,
  FontFamily,
  FontHeight,
  FontParagraphSpacing,
  FontSize,
  FontSpacing,
  FontWeight,
  SpacingValues,
} from 'theme-token-manager'
import {
  BaseThemeConfig,
  ColorValues,
  FontValues,
  FoundationValues,
  NestedOptional,
  PartialTheme,
  ResultTheme,
  ThemeColorValue,
  ThemePalette,
  ThemePaletteBorder,
  ThemePaletteBorderValues,
  ThemePaletteIcon,
  ThemePaletteIconValues,
  ThemePaletteSurface,
  ThemePaletteSurfaceValues,
  ThemePaletteText,
  ThemePaletteTextValues,
  Theme as TokenTheme,
} from 'theme-token-manager/theme/types'

type Theme = Omit<ResultTheme, 'palette'> & {
  palette: ThemePalette<string>
}

type InputTheme = TokenTheme

export type {
  BaseThemeConfig,
  BorderRadiusValues,
  BorderWidthValues,
  ColorScaleStringValues,
  ColorScaleValues,
  ColorValues,
  DimensionValues,
  FontFamily,
  FontHeight,
  FontParagraphSpacing,
  FontSize,
  FontSpacing,
  FontValues,
  FontWeight,
  FoundationValues,
  InputTheme,
  NestedOptional,
  PartialTheme,
  ResultTheme,
  SpacingValues,
  Theme,
  ThemeColorValue,
  ThemePalette,
  ThemePaletteBorder,
  ThemePaletteBorderValues,
  ThemePaletteIcon,
  ThemePaletteIconValues,
  ThemePaletteSurface,
  ThemePaletteSurfaceValues,
  ThemePaletteText,
  ThemePaletteTextValues,
}
